CREATE TABLE photos (
  id INT NOT NULL AUTO_INCREMENT,
  imageName VARCHAR(250),
  PRIMARY KEY (id)
);

CREATE TABLE tmp (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (id)
);