CREATE SCHEMA IF NOT EXISTS testdb;

CREATE TABLE IF NOT EXISTS Photo (
PhotoID INT NOT NULL AUTO_INCREMENT,
PhotoName VARCHAR(250) NOT NULL,
PRIMARY KEY (PhotoID)
);

CREATE TABLE IF NOT EXISTS PhotoTag (
PhotoTagID INT NOT NULL AUTO_INCREMENT,
PhotoID INT NOT NULL,
TagID INT NOT NULL,
PRIMARY KEY (PhotoTagID)
);

CREATE TABLE IF NOT EXISTS Tag (
TagID INT NOT NULL AUTO_INCREMENT,
TagName VARCHAR(250) NOT NULL,
PRIMARY KEY (TagID)
);